<a href="https://colab.research.google.com/github/Fareed-Ahmad7/tensorflow-learning/blob/main/Tensorflow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [ ]:
# zero dimensional tensors / zero rank tensors
tensor1 = tf.Variable("farid", tf.string) # string tensor
tensor2 = tf.Variable(546, tf.int32) # int32 tensor
tensor3 = tf.Variable(5.346, tf.float32) # float32 tensor

tensor4 = tf.Variable(["farid", "ahmed"], tf.string)
tensor5 = tf.Variable([["farid", "shaik"],["ahmed", "Ahmed"]], tf.string)

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)
tf.rank(tensor1)
tf.rank(tensor4)
tf.rank(tensor5)

tensor4.shape # shape is no.of elements that exist in each dimension 
tensor5.shape

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'farid'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=546>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.346>


TensorShape([2, 2])

# **Changing Shape of tensor**

---




In [ ]:
tensor6 = tf.Variable([[["apple", "banana", "fruit1"],
                         ["apple2", "banana2", "fruit2"]],
                       
                       [["mango", "guava", "fruit3"], 
                        ["apple3", "banana4", "fruit4"]],
                       
                        [["bluberry", "blackberry", "fruit5"], 
                         ["apple3", "banana3", "fruit6"]]
                       ])
tensor6.shape
print(tensor6)

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=string, numpy=
array([[[b'apple', b'banana', b'fruit1'],
        [b'apple2', b'banana2', b'fruit2']],

       [[b'mango', b'guava', b'fruit3'],
        [b'apple3', b'banana4', b'fruit4']],

       [[b'bluberry', b'blackberry', b'fruit5'],
        [b'apple3', b'banana3', b'fruit6']]], dtype=object)>


In [ ]:
tensor7 = tf.reshape(tensor6, [3, 3, 2])
print(tensor7)

tf.Tensor(
[[[b'apple' b'banana']
  [b'fruit1' b'apple2']
  [b'banana2' b'fruit2']]

 [[b'mango' b'guava']
  [b'fruit3' b'apple3']
  [b'banana4' b'fruit4']]

 [[b'bluberry' b'blackberry']
  [b'fruit5' b'apple3']
  [b'banana3' b'fruit6']]], shape=(3, 3, 2), dtype=string)


In [ ]:
tensor7 = tf.reshape(tensor6, [2, 3, 3])
print(tensor7)

tf.Tensor(
[[[b'apple' b'banana' b'fruit1']
  [b'apple2' b'banana2' b'fruit2']
  [b'mango' b'guava' b'fruit3']]

 [[b'apple3' b'banana4' b'fruit4']
  [b'bluberry' b'blackberry' b'fruit5']
  [b'apple3' b'banana3' b'fruit6']]], shape=(2, 3, 3), dtype=string)


In [ ]:
tensor7 = tf.reshape(tensor6, [2, 3, -1]) # -1 tells the tensor to calculate the size of that dimension in that place
print(tensor7)

tf.Tensor(
[[[b'apple' b'banana' b'fruit1']
  [b'apple2' b'banana2' b'fruit2']
  [b'mango' b'guava' b'fruit3']]

 [[b'apple3' b'banana4' b'fruit4']
  [b'bluberry' b'blackberry' b'fruit5']
  [b'apple3' b'banana3' b'fruit6']]], shape=(2, 3, 3), dtype=string)


# **Types of Tensors**

---





1.   Variable
2.   Constant
3.   Placeholder
4.   SparseTensor

In [ ]:
tensor8 = tf.ones(45 , tf.int32)
tensor8 = tf.zeros(45 , tf.int32)
print(tensor8)

tf.Tensor(
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0], shape=(45,), dtype=int32)


In [ ]:
t9 = tf.zeros([5, 5, 5, 5])

In [ ]:
t9 = tf.reshape(t9, [625])
print(t9)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 